use_frameworks!

platform :ios, '8.0'

target 'CLKitHelp_Example' do
  pod 'CLKitHelp', :path => '../'

  target 'CLKitHelp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
